--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

-- Started on 2025-06-14 15:09:59

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4946 (class 1262 OID 16529)
-- Name: bdfit_link; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE bdfit_link WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Portuguese_Brazil.1252';


ALTER DATABASE bdfit_link OWNER TO postgres;

\connect bdfit_link

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4947 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16561)
-- Name: Clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Clientes" (
    "ID" integer NOT NULL,
    "Nome" character varying(255) NOT NULL,
    "Sexo" character varying(255) NOT NULL,
    "Idade" date NOT NULL,
    "Endereço" character varying(255) NOT NULL,
    "Telefone" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Turno" character varying(255) NOT NULL,
    "Senha_hash" text NOT NULL,
    "Foto" bytea,
    "Data_cadastro" date NOT NULL,
    "Observacao" text,
    "Data_Nascimento" date,
    "Altura" numeric,
    "Meta" character varying(255)
);


ALTER TABLE public."Clientes" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16560)
-- Name: Clientes_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Clientes" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16569)
-- Name: Consultas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Consultas" (
    "ID" integer NOT NULL,
    "Data_consulta" date NOT NULL,
    "Peso" numeric,
    "Altura" numeric,
    "IMC" numeric,
    "Cintura" numeric,
    "Quadril" numeric,
    "Observacao" text,
    "Fotos" bytea,
    "Prontuario" bytea,
    "Consulta_Agendada" date,
    "ID_Paciente" integer NOT NULL,
    "ID_Nutricionista" integer NOT NULL,
    "ID_Personal" integer NOT NULL,
    "ID_Treinos" integer NOT NULL
);


ALTER TABLE public."Consultas" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16568)
-- Name: Consultas_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Consultas" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Consultas_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16545)
-- Name: Nutricionistas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Nutricionistas" (
    "ID" integer NOT NULL,
    "Nome" character varying(255) NOT NULL,
    "Idade" date NOT NULL,
    "Endereço" character varying(255) NOT NULL,
    "Telefone" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "CRN" character varying(255) NOT NULL,
    "Senha_hash" text NOT NULL,
    "Foto" bytea NOT NULL,
    "Data_cadastro" date NOT NULL
);


ALTER TABLE public."Nutricionistas" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16544)
-- Name: Nutricionistas_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Nutricionistas" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Nutricionistas_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16553)
-- Name: Personal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Personal" (
    "ID" integer NOT NULL,
    "Nome" character varying(255) NOT NULL,
    "Idade" date NOT NULL,
    "Endereço" character varying(255) NOT NULL,
    "Telefone" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "CREF" character varying(255) NOT NULL,
    "Senha_hash" text NOT NULL,
    "Foto" bytea NOT NULL,
    "Data_cadastro" date NOT NULL
);


ALTER TABLE public."Personal" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16552)
-- Name: Personal_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Personal" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Personal_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16531)
-- Name: Treinos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Treinos" (
    "ID" integer NOT NULL,
    "Data_Treino" date NOT NULL,
    "Exercicios" text,
    "Observacao" text,
    "ID_Paciente" integer NOT NULL,
    "ID_Personal" integer NOT NULL,
    "Completo" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Treinos" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16530)
-- Name: Treinos_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Treinos" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Treinos_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4938 (class 0 OID 16561)
-- Dependencies: 222
-- Data for Name: Clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4940 (class 0 OID 16569)
-- Dependencies: 224
-- Data for Name: Consultas; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4934 (class 0 OID 16545)
-- Dependencies: 218
-- Data for Name: Nutricionistas; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4936 (class 0 OID 16553)
-- Dependencies: 220
-- Data for Name: Personal; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4932 (class 0 OID 16531)
-- Dependencies: 216
-- Data for Name: Treinos; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4948 (class 0 OID 0)
-- Dependencies: 221
-- Name: Clientes_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Clientes_ID_seq"', 1, false);


--
-- TOC entry 4949 (class 0 OID 0)
-- Dependencies: 223
-- Name: Consultas_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Consultas_ID_seq"', 1, false);


--
-- TOC entry 4950 (class 0 OID 0)
-- Dependencies: 217
-- Name: Nutricionistas_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Nutricionistas_ID_seq"', 1, false);


--
-- TOC entry 4951 (class 0 OID 0)
-- Dependencies: 219
-- Name: Personal_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Personal_ID_seq"', 1, false);


--
-- TOC entry 4952 (class 0 OID 0)
-- Dependencies: 215
-- Name: Treinos_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Treinos_ID_seq"', 1, false);


--
-- TOC entry 4769 (class 2606 OID 16567)
-- Name: Clientes Clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "Clientes_pkey" PRIMARY KEY ("ID");


--
-- TOC entry 4771 (class 2606 OID 16581)
-- Name: Consultas Consultas_ID_Nutricionista_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultas"
    ADD CONSTRAINT "Consultas_ID_Nutricionista_key" UNIQUE ("ID_Nutricionista");


--
-- TOC entry 4773 (class 2606 OID 16579)
-- Name: Consultas Consultas_ID_Paciente_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultas"
    ADD CONSTRAINT "Consultas_ID_Paciente_key" UNIQUE ("ID_Paciente");


--
-- TOC entry 4775 (class 2606 OID 16583)
-- Name: Consultas Consultas_ID_Personal_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultas"
    ADD CONSTRAINT "Consultas_ID_Personal_key" UNIQUE ("ID_Personal");


--
-- TOC entry 4777 (class 2606 OID 16585)
-- Name: Consultas Consultas_ID_Treinos_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultas"
    ADD CONSTRAINT "Consultas_ID_Treinos_key" UNIQUE ("ID_Treinos");


--
-- TOC entry 4779 (class 2606 OID 16577)
-- Name: Consultas Consultas_ID_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultas"
    ADD CONSTRAINT "Consultas_ID_key" UNIQUE ("ID");


--
-- TOC entry 4781 (class 2606 OID 16575)
-- Name: Consultas Consultas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultas"
    ADD CONSTRAINT "Consultas_pkey" PRIMARY KEY ("ID", "ID_Paciente", "ID_Nutricionista", "ID_Personal", "ID_Treinos");


--
-- TOC entry 4765 (class 2606 OID 16551)
-- Name: Nutricionistas Nutricionistas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Nutricionistas"
    ADD CONSTRAINT "Nutricionistas_pkey" PRIMARY KEY ("ID");


--
-- TOC entry 4767 (class 2606 OID 16559)
-- Name: Personal Personal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Personal"
    ADD CONSTRAINT "Personal_pkey" PRIMARY KEY ("ID");


--
-- TOC entry 4757 (class 2606 OID 16541)
-- Name: Treinos Treinos_ID_Paciente_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treinos"
    ADD CONSTRAINT "Treinos_ID_Paciente_key" UNIQUE ("ID_Paciente");


--
-- TOC entry 4759 (class 2606 OID 16543)
-- Name: Treinos Treinos_ID_Personal_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treinos"
    ADD CONSTRAINT "Treinos_ID_Personal_key" UNIQUE ("ID_Personal");


--
-- TOC entry 4761 (class 2606 OID 16539)
-- Name: Treinos Treinos_ID_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treinos"
    ADD CONSTRAINT "Treinos_ID_key" UNIQUE ("ID");


--
-- TOC entry 4763 (class 2606 OID 16537)
-- Name: Treinos Treinos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treinos"
    ADD CONSTRAINT "Treinos_pkey" PRIMARY KEY ("ID", "ID_Paciente", "ID_Personal");


--
-- TOC entry 4786 (class 2606 OID 16596)
-- Name: Clientes Clientes_ID_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "Clientes_ID_fkey" FOREIGN KEY ("ID") REFERENCES public."Consultas"("ID_Paciente");


--
-- TOC entry 4787 (class 2606 OID 16611)
-- Name: Clientes Clientes_ID_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "Clientes_ID_fkey1" FOREIGN KEY ("ID") REFERENCES public."Treinos"("ID_Paciente");


--
-- TOC entry 4783 (class 2606 OID 16586)
-- Name: Nutricionistas Nutricionistas_ID_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Nutricionistas"
    ADD CONSTRAINT "Nutricionistas_ID_fkey" FOREIGN KEY ("ID") REFERENCES public."Consultas"("ID_Nutricionista");


--
-- TOC entry 4784 (class 2606 OID 16591)
-- Name: Personal Personal_ID_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Personal"
    ADD CONSTRAINT "Personal_ID_fkey" FOREIGN KEY ("ID") REFERENCES public."Consultas"("ID_Personal");


--
-- TOC entry 4785 (class 2606 OID 16606)
-- Name: Personal Personal_ID_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Personal"
    ADD CONSTRAINT "Personal_ID_fkey1" FOREIGN KEY ("ID") REFERENCES public."Treinos"("ID_Personal");


--
-- TOC entry 4782 (class 2606 OID 16601)
-- Name: Treinos Treinos_ID_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treinos"
    ADD CONSTRAINT "Treinos_ID_fkey" FOREIGN KEY ("ID") REFERENCES public."Consultas"("ID_Treinos");


-- Completed on 2025-06-14 15:10:01

--
-- PostgreSQL database dump complete
--

